In [1]:


import mobster as mb

import numpy as np



Bad key "text.kerning_factor" on line 4 in
/Users/salvatore/miniconda3/envs/hmobster/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test_patch.mplstyle.
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.1.3/matplotlibrc.template
or from the matplotlib source distribution


In [2]:
data = mb.load_example_data("./")

#data = data["1:1"]

In [16]:
fitted = mb.fit_mobster(data,1,1,purity = 1,  truncated_pareto=True, max_it = 200, lr = 0.05,  e = 0.0001, lrd_gamma = 0.1,   
        number_of_trials_k= 100, prior_lims_k=[0.1,10000], prior_lims_clonal=[0.1,10000.], number_of_trials_clonal_mean= 300.)

Running MOBSTER on 5 karyotypes with 1 subclones.
Fitting a model with tail
tensor([[0.2650, 0.1815, 0.1400]])
tensor([[0.5145, 0.2650]])
tensor([[0.2650, 0.1815, 0.1400]])
tensor([[0.5145, 0.2650]])
tensor([[0.2650, 0.1815, 0.1400]])
tensor([[0.5145, 0.2650]])
tensor([[0.2650, 0.1815, 0.1400]])
tensor([[0.5145, 0.2650]])
tensor([[0.2650, 0.1815, 0.1400]])
tensor([[0.5145, 0.2650]])
tensor([[0.2650, 0.1815, 0.1400]])
tensor([[0.5145, 0.2650]])
tensor([[0.2650, 0.1815, 0.1400]])
tensor([[0.5145, 0.2650]])
tensor([[0.2650, 0.1815, 0.1400]])
tensor([[0.5145, 0.2650]])
tensor([[0.2650, 0.1815, 0.1400]])
tensor([[0.5145, 0.2650]])
tensor([[0.2650, 0.1815, 0.1400]])
tensor([[0.5145, 0.2650]])
tensor([[0.2650, 0.1815, 0.1400]])
tensor([[0.5145, 0.2650]])
tensor([[0.2650, 0.1815, 0.1400]])
tensor([[0.5145, 0.2650]])
tensor([[0.2650, 0.1815, 0.1400]])
tensor([[0.5145, 0.2650]])
tensor([[0.2650, 0.1815, 0.1400]])
tensor([[0.5145, 0.2650]])
tensor([[0.2650, 0.1815, 0.1400]])
tensor([[0.5145, 0.26

ELBO: -3018.545154325  :  88%|████████▊ | 175/200 [00:09<00:01, 18.53it/s]


In [17]:

mb.plot_results(data, fitted, output= "cane.png", drivers=None)

In [9]:
fitted["model_parameters"]["1:0"]



{'cluster_probs': array([[3.45499553e-02, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         4.76203151e-02, 2.16399878e-02, 0.00000000e+00, 1.49541572e-02,
         7.47915953e-02, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 4.30292100e-01, 0.00000000e+00,
         0.00000000e+00, 1.90996230e-02, 0.00000000e+00, 0.00000000e+00,
         1.89935844e-02, 1.06400270e-02, 1.89935844e-02, 3.54304388e-02,
         3.37497666e-02, 6.46218657e-02, 0.00000000e+00, 7.77719170e-02,
         2.05958709e-01, 0.00000000e+00, 1.44702215e-02, 3.66629958e-02,
         1.59798693e-02, 2.72649359e-02, 2.16399878e-02, 4.76203151e-02,
         0.00000000e+00, 0.00000000e+00, 1.25189861e-02, 0.00000000e+00,
         1.44702215e-02, 0.0000000

1